
# Keg sizes from here:
# http://en.wikipedia.org/wiki/Keg
KEG_SIZE_CHOICES = (
    (18.9, 'Sixth Barrel 18.9L'),
    (29.33, 'Quarter Barrel 29.3L'),
    (58.66, 'Half Barrel 58.66L'),
)

# Beer sizes from here:
# @TODO: Get reference
BEER_TYPE_CHOICES = (
    ('def', 'DEFAULT'),
    ('alt', 'Altbier'),
    ('amb', 'Amber ale'),
    ('bar', 'Barley wine'),
    ('ber', 'Berliner weisse'),
    ('bie', 'Biere de Garde'),
    ('bit', 'Bitter'),
    ('blo', 'Blonde Ale'),
    ('boc', 'Bock (Traditional)'),
    ('bro', 'Brown ale'),
    ('cal', 'California Common'),
    ('cre', 'Cream Ale'),
    ('dor', 'Dortmunder Export'),
    ('dop', 'Doppelbock'),
    ('dun', 'Dunkel'),
    ('duw', 'Dunkelweizen'),
    ('eis', 'Eisbock'),
    ('fru', 'Fruit lambic'),
    ('gol', 'Golden Ale'),
    ('gos', 'Gose'),
    ('gue', 'Gueuze'),
    ('hef', 'Hefeweizen'),
    ('hel', 'Helles'),
    ('ind', 'India pale ale'),
    ('kol', 'Kolsch'),
    ('lam', 'Lambic'),
    ('lig', 'Light ale'),
    ('mai', 'Maibock/Helles bock'),
    ('mal', 'Malt liquor'),
    ('mil', 'Mild'),
    ('okt', 'Oktoberfestbier/Marzenbier'),
    ('old', 'Old ale'),
    ('oud', 'Oud bruin'),
    ('pal', 'Pale ale'),
    ('pil', 'Pilsener/Pilsner/Pils'),
    ('por', 'Porter'),
    ('red', 'Red ale'),
    ('rog', 'Roggenbier'),
    ('sai', 'Saison'),
    ('sco', 'Scotch ale'),
    ('ste', 'Steam beer'),
    ('sto', 'Stout'),
    ('sch', 'Schwarzbier'),
    ('vie', 'Vienna lager'),
    ('wit', 'Witbier'),
    ('wes', 'Weissbier'),
    ('wez', 'Weizenbock'),
)
