BEER_TYPE_CHOICES = (
    ('alt', 'Altbier'),
    ('amb', 'Amber ale'),
    ('bar', 'Barley wine'),
    ('ber', 'Berliner weisse'),
    ('bie', 'Biere de Garde'),
    ('bit', 'Bitter'),
    ('blo', 'Blonde Ale'),
    ('boc', 'Bock (Traditional)'),
    ('bro', 'Brown ale'),
    ('cal', 'California Common'),
    ('cre', 'Cream Ale'),
    ('dor', 'Dortmunder Export'),
    ('dop', 'Doppelbock'),
    ('dun', 'Dunkel'),
    ('duw', 'Dunkelweizen'),
    ('eis', 'Eisbock'),
    ('fru', 'Fruit lambic'),
    ('gol', 'Golden Ale'),
    ('gos', 'Gose'),
    ('gue', 'Gueuze'),
    ('hef', 'Hefeweizen'),
    ('hel', 'Helles'),
    ('ind', 'India pale ale'),
    ('kol', 'Kolsch'),
    ('lam', 'Lambic'),
    ('lig', 'Light ale'),
    ('mai', 'Maibock/Helles bock'),
    ('mal', 'Malt liquor'),
    ('mil', 'Mild'),
    ('okt', 'Oktoberfestbier/Marzenbier'),
    ('old', 'Old ale'),
    ('oud', 'Oud bruin'),
    ('pal', 'Pale ale'),
    ('pil', 'Pilsener/Pilsner/Pils'),
    ('por', 'Porter'),
    ('red', 'Red ale'),
    ('rog', 'Roggenbier'),
    ('sai', 'Saison'),
    ('sco', 'Scotch ale'),
    ('ste', 'Steam beer'),
    ('sto', 'Stout'),
    ('sch', 'Schwarzbier'),
    ('vie', 'Vienna lager'),
    ('wit', 'Witbier'),
    ('wes', 'Weissbier'),
    ('wez', 'Weizenbock'),
)
